---
title: Hocus Photus
name: Hocus Photus
description:  Art and Science Network
url: https://cool-spinach-98452.netlify.com/
baseurl: "/"
permalink: "/:title/"
layout_style: overflow
palette: blue
header:
  title: Hocus Photus
  tagline: Art and Science Network
  profile_img: "/images/Hocus-Photus-logo-front-1.jpg"
  bg: dark
  has_nav: true
  has_social: true
footer:
  content: "&copy; 2019 - Hocus Photus. All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
