---
title: Hocus Photus
baseurl: "/"
permalink: "/:title/"
layout_style: overflow
palette: blue
header:
  title: Hocus Photus
  tagline: Art and Science Network
  profile_img: "/images/logo-black.jpg"
  bg: light
  has_nav: true
  has_social: true
footer:
  content: "&copy; All rights reserved."
  links:
  - text: Made with Stackbit
    url: https://www.stackbit.com
    new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
