[build]
publish = "_site"
command = "jekyll build"
environment = { JEKYLL_ENV = “netlify” }
[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"
