[build]
publish = "_site"
# Default build command.
command = "echo 'default context'"
[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"
