backend:
  name: github
  repo: achillesn/cool-spinach
  branch: master

media_folder: images
public_folder: /images

collections:
  - name: posts_root
    label: Άρθρα (γενικά)
    folder: _posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: &post_fields
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - { label: Date, name: date, widget: datetime }
      - { label: Featured Image, name: thumb_img_path, widget: image, required: false }
      - { label: Alternative Featured Image, name: content_img_path, widget: image, required: false }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Canonical URL, name: canonical_url, widget: string, required: false }
      - { label: Category, name: categories, widget: list, required: false }
      - { label: Layout, name: layout, widget: hidden, default: post }
      - { label: Κείμενο, name: body, widget: markdown }

  - name: iconic_hacks
    label: ICONIC HACKS
    folder: _posts/ICONIC HACKS
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: paralliloi_kosmoi
    label: ICONIC HACKS / Παράλληλοι Κόσμοι
    folder: _posts/ICONIC HACKS/PARALLILOI KOSMOI
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: virtual_connections
    label: ICONIC HACKS / Virtual Connections III
    folder: _posts/ICONIC HACKS/Virtual Connections III
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: epg
    label: ICONIC HACKS / e-PG
    folder: _posts/ICONIC HACKS/e-PG
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: ephotogames3
    label: ICONIC HACKS / e-photogames 3
    folder: _posts/ICONIC HACKS/e-photogames 3
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: photologoi
    label: ICONIC HACKS / Photologoi
    folder: _posts/ICONIC HACKS/photologoi
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: nevi
    label: NEVI
    folder: _posts/NEVI
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: nena
    label: NEVI / NENA
    folder: _posts/NEVI/NENA
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: random
    label: RANDOM
    folder: _posts/RANDOM
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: studium
    label: StudiUm
    folder: _posts/StudiUm
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: cyclops_eye
    label: THE CYCLOP's EYE
    folder: _posts/THE CYCLOP's EYE
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: anodus
    label: THE CYCLOP's EYE / ANODUS
    folder: _posts/THE CYCLOP's EYE/ANODUS
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: news
    label: News
    folder: _posts/news
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: news_eya
    label: News / EYA
    folder: _posts/news/EYA
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

  - name: syllogikes
    label: ΣΥΛΛΟΓΙΚΕΣ ΑΦΗΓΗΣΕΙΣ
    folder: _posts/ΣΥΛΛΟΓΙΚΕΣ ΑΦΗΓΗΣΕΙΣ
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: *post_fields

      - name: pages
    label: Σελίδες
    files:
      - name: about
        label: About
        file: about.md
        fields: &page_fields
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string, required: false }
          - { label: Image, name: img_path, widget: image, required: false }
          - { label: Layout, name: layout, widget: hidden, default: page }
          - { label: Κείμενο, name: body, widget: markdown }
      - name: hocus_contents
        label: Hocus Contents
        file: hocus-contents.md
        fields: *page_fields
      - name: studium
        label: StudiUm
        file: studium.md
        fields: *page_fields
      - name: style_guide
        label: Style Guide
        file: style-guide.md
        fields: *page_fields
