backend:
  name: github
  repo: achillesn/cool-spinach
  branch: master

media_folder: images
public_folder: /images

collections:
  - name: home
    label: Αρχική σελίδα
    files:
      - name: home_page
        label: Hocus Domus (Αρχική)
        file: index.md
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Layout, name: layout, widget: hidden, default: home }
          - label: Ενότητες
            name: sections
            widget: list
            types:
              - label: Κείμενο με εικόνα
                name: contentblock
                widget: object
                fields:
                  - { label: Template, name: template, widget: hidden, default: contentblock }
                  - { label: Component, name: component, widget: hidden, default: content_block.html }
                  - { label: Τίτλος, name: title, widget: string, required: false }
                  - { label: Section ID, name: section_id, widget: string, required: false }
                  - { label: Κείμενο, name: content, widget: markdown, required: false }
                  - { label: Εικόνα, name: image, widget: image, required: false }
                  - label: Κουμπιά
                    name: actions
                    widget: list
                    required: false
                    fields: &action_fields
                      - { label: Κείμενο κουμπιού, name: label, widget: string }
                      - { label: Διεύθυνση, name: url, widget: string }
              - label: Λίστα άρθρων
                name: postsblock
                widget: object
                fields:
                  - { label: Template, name: template, widget: hidden, default: postsblock }
                  - { label: Component, name: component, widget: hidden, default: posts_block.html }
                  - { label: Τίτλος, name: title, widget: string, required: false }
                  - { label: Section ID, name: section_id, widget: string, required: false }
                  - { label: Πόσα άρθρα να δείχνει, name: num_posts_displayed, widget: number, value_type: int, required: false }
                  - { label: Κουμπιά, name: actions, widget: list, required: false, fields: *action_fields }
              - label: Hero (μεγάλη επικεφαλίδα)
                name: heroblock
                widget: object
                fields:
                  - { label: Template, name: template, widget: hidden, default: heroblock }
                  - { label: Component, name: component, widget: hidden, default: hero_block.html }
                  - { label: Τίτλος, name: title, widget: string, required: false }
                  - { label: Section ID, name: section_id, widget: string, required: false }
                  - { label: Κείμενο, name: content, widget: markdown, required: false }
                  - { label: Κουμπιά, name: actions, widget: list, required: false, fields: *action_fields }

  - name: posts_root
    label: Άρθρα (γενικά)
    folder: _posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: &post_fields
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - { label: Date, name: date, widget: datetime }
      - { label: Featured Image, name: thumb_img_path, widget: image, required: false }
      - { label: Alternative Featured Image, name: content_img_path, widget: image, required: false }
      - { label: Excerpt, name: excerpt, widget: text, required: false }
      - { label: Canonical URL, name: canonical_url, widget: string,
